version: "3"

services:
  app:
    build:
      context: .
    environment:
      - AUTH0_ID=<AUTH0_ID>

  myproxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 443:443
