version: "3"

services:
  app:
    build:
      context: .
    environment:
      - AUTH0_ID=<AUTH0_ID>

  myproxy:
    image: nginx:1.21.0
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
